
export const school = [
    {
     "Timestamp": "5\/16\/2024 19:06:29",
     "nameOfSchoolInstitution": "Kshetramahabaleshwar ZP school",
     "Type of institution\/school": "Others (specify)",
     "District": "Mahabaleshwar",
     "State": "Maharashtra",
     "fullAddressWithPinCode": "Zilla Parishad school, Kshetramahabaleshwar, AT post, Mahabaleshwar, District Mahahbaleshwar, Pin -412806",
     "Name of the Principal and Management ": "Sushant Motling",
     "Contact number of the Principal\/Management": 9890150842,
     "Name of the teacher\/coordinator for training and managing the library": "Jyoti Kadam",
     "Contact details of the coordinator\/teacher": 9403632014,
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "Yes",
     "Number of Students - Balwadi - class 1": 6,
     "Number of Students - class 2 - class 4": 24,
     "Number of Students - class 5 and above": 46,
     "Referred by": "Lata",
     "Total No of Toys": 76,
     "Date of despatch ": "25\/5\/24",
     "Mode of despatch": "by volovo bus",
     "Tracking details": "bus driver",
     "Date of delivery": "26\/05\/24",
     "Completed": true
    },
    {
     "code": 29,
     "Timestamp": "5\/16\/2024 19:12:31",
     "nameOfSchoolInstitution": "Pragati wheel school",
     "Type of institution\/school": "Trust",
     "District": "Delhi",
     "State": "Delhi",
     "fullAddressWithPinCode": "C-240, Pandav Nagar, Delhi - 110092 (Near Radha Krishna Mandir, Opposite Mother Diary)",
     "Name of the Principal and Management ": "Raman Khanna ",
     "Contact number of the Principal\/Management": 9811310917,
     "Name of the teacher\/coordinator for training and managing the library": "Raman Khanna ",
     "Contact details of the coordinator\/teacher": 9811310917,
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "Yes",
     "Number of Students - Balwadi - class 1": 0,
     "Number of Students - class 2 - class 4": 25,
     "Number of Students - class 5 and above": 0,
     "Referred by": "Pushpa",
     "Total No of Toys": 25,
     "Completed": true
    },
    {
     "Timestamp": "5\/16\/2024 19:22:09",
     "nameOfSchoolInstitution": "Paras Balbhavan",
     "Type of institution\/school": "Others (specify)",
     "Village name  if any": "Titwala",
     "District": "Thane",
     "State": "Maharashtra",
     "fullAddressWithPinCode": "Paras Balbhavan, near ZP school, Maskal, Titwala (E), Taluka Kalyan, Dist Thane - 421605",
     "Name of the Principal and Management ": "Sangita Gunjal",
     "Contact number of the Principal\/Management": 8652069665,
     "Name of the teacher\/coordinator for training and managing the library": "Sangita Gunjal",
     "Contact details of the coordinator\/teacher": 8652069665,
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "Yes",
     "Number of Students - Balwadi - class 1": 0,
     "Number of Students - class 2 - class 4": 25,
     "Number of Students - class 5 and above": 25,
     "Referred by": "Sundar sir",
     "Total No of Toys": 50,
     "Completed": true
    },
    {
     "Timestamp": "5\/16\/2024 19:53:45",
     "nameOfSchoolInstitution": "HINDU MIDDLE SCHOOL, HARIKESAVANALLUR ",
     "Type of institution\/school": "Semi aided school",
     "Village name  if any": "HARIKESAVANALLUR ",
     "District": "TIRUNELVELI ",
     "State": "Tamil Nadu",
     "fullAddressWithPinCode": "No 26, NORTH STREET , HARIKESAVANALLUR  627426",
     "Name of the Principal and Management ": "Ramchandar M",
     "Contact number of the Principal\/Management": 9750259000,
     "Name of the teacher\/coordinator for training and managing the library": "Jesmala S",
     "Contact details of the coordinator\/teacher": 9994166499,
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "Yes",
     "Number of Students - Balwadi - class 1": 14,
     "Number of Students - class 2 - class 4": 43,
     "Number of Students - class 5 and above": 130,
     "Referred by": "Mrs.Pushpa",
     "Total No of Toys": 187,
     "Date of despatch ": "26\/5\/2024",
     "Mode of despatch": "Courier circlepro",
     "Tracking details": 53501236740,
     "Date of delivery": "05\/06\/24",
     "Completed": true
    },
    {
     "Timestamp": "5\/17\/2024 14:52:28",
     "nameOfSchoolInstitution": "Vivekananda vidyalayam nursery and primary school ",
     "Board affiliated to and Medium  of instruction": "Tamil Nadu State board and English",
     "Type of institution\/school": "Private school",
     "District": "Tenkasi ",
     "State": "Tamilnadu ",
     "fullAddressWithPinCode": "20\/56 Keela avani moola veedhi,Tenkasi 627811",
     "Name of the Principal and Management ": "Mithra Sakthivel",
     "Contact number of the Principal\/Management": 9965515185,
     "Name of the teacher\/coordinator for training and managing the library": "Ms.Karthika",
     "Contact details of the coordinator\/teacher": 9003314496,
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "Yes",
     "Pictures of the library room and cupboard": "https:\/\/drive.google.com\/open?id=1SMGQPv8utfa07OpsFSdw7aT-e78F6xeh, https:\/\/drive.google.com\/open?id=1QjYV9WQy0XJfpAYFP-trYxFLlRNkN5D8, https:\/\/drive.google.com\/open?id=1thtzXfC24apQfZC0r46a0mga38BCwrWy, https:\/\/drive.google.com\/open?id=1gnA2IWy7pMNqASoS1UNkc7SABMPUFHVd",
     "Number of Students - Balwadi - class 1": 62,
     "Number of Students - class 2 - class 4": 46,
     "Number of Students - class 5 and above": 18,
     "Referred by": "Aishwarya Joshi",
     "Total No of Toys": 126,
     "Date of despatch ": "10\/06\/24",
     "Mode of despatch": "Courier circlepro",
     "Tracking details": 53503104225,
     "Date of delivery": "18\/06\/24",
     "Completed": true
    },
    {
     "Timestamp": "5\/22\/2024 14:03:38",
     "nameOfSchoolInstitution": "Swapnopuron Shiksha Niketan",
     "Type of institution\/school": "NGO",
     "Village name  if any": "Jora Bottola, Hingalganj",
     "District": "North 24 Paragana",
     "State": "West bengal",
     "fullAddressWithPinCode": "Jora bottola, Hingalganj, North 24 paragana, 743435",
     "Name of the Principal and Management ": "Saratupa Majumder ",
     "Contact number of the Principal\/Management": 8420579906,
     "Name of the teacher\/coordinator for training and managing the library": "Manosij Bandhopadhay",
     "Contact details of the coordinator\/teacher": 8116424917,
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "No",
     "Number of Students - Balwadi - class 1": 240,
     "Number of Students - class 2 - class 4": 91,
     "Number of Students - class 5 and above": 37,
     "Referred by": "Bhumi",
     "Board affiliated to and Medium  of instruction(1)": " ",
     "Total No of Toys": 368,
     "Date of despatch ": "21\/06\/24",
     "Mode of despatch": "Courier circlepro",
     "Date of delivery": "26\/06\/24",
     "Completed": true
    },
    {
     "Timestamp": "7\/30\/2024 11:52:36",
     "nameOfSchoolInstitution": "Harakade",
     "Type of institution\/school": "Others (specify)",
     "Village name  if any": "Harakade",
     "District": "Uttarkannada",
     "State": "Karnataka",
     "fullAddressWithPinCode": "Harakade, Divgi, Kumta, Uttarkannada, Karnataka - 581343.",
     "Name of the Principal and Management ": "Radha Gouda",
     "Contact number of the Principal\/Management": 9980295416,
     "Name of the teacher\/coordinator for training and managing the library": "Radha Gouda",
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "Yes",
     "Number of Students - Balwadi - class 1": 22,
     "Number of Students - class 2 - class 4": 0,
     "Number of Students - class 5 and above": 0,
     "Referred by": "Sujeet",
     "Total No of Toys": 22,
     "Completed": true
    },
    {
     "Timestamp": "7\/30\/2024 12:00:15",
     "nameOfSchoolInstitution": "Gundmi ",
     "Type of institution\/school": "Others (specify)",
     "Village name  if any": "Gundmi",
     "District": "Sasthana",
     "State": "Karnataka",
     "fullAddressWithPinCode": "Anganvadi center Gundmi, Sasthana post, Karnataka- 576226.",
     "Name of the Principal and Management ": "Suma",
     "Contact number of the Principal\/Management": 7204555658,
     "Name of the teacher\/coordinator for training and managing the library": "suma",
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "Yes",
     "Number of Students - Balwadi - class 1": 34,
     "Number of Students - class 2 - class 4": 0,
     "Number of Students - class 5 and above": 0,
     "Referred by": "Sujeet",
     "Total No of Toys": 34,
     "Completed": true
    },
    {
     "Timestamp": "8\/1\/2024 12:27:59",
     "nameOfSchoolInstitution": "Ganesh Mondal",
     "Type of institution\/school": "Others (specify)",
     "Village name  if any": "Ganesh Mondal",
     "District": "North 24 Paragana",
     "State": "West Bengal",
     "fullAddressWithPinCode": "37c bediadanga, masjidbari bylane, kolkata 700040",
     "Name of the Principal and Management ": "Saratupa Majumder ",
     "Contact number of the Principal\/Management": 8420579906,
     "Name of the teacher\/coordinator for training and managing the library": "Manosij Bandhopadhay",
     "Contact details of the coordinator\/teacher": 8116424917,
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "No",
     "Number of Students - Balwadi - class 1": 129,
     "Number of Students - class 2 - class 4": 27,
     "Number of Students - class 5 and above": "-",
     "Referred by": "Bhumi",
     "Board affiliated to and Medium  of instruction(1)": "-",
     "Completed": true
    },
    {
     "Timestamp": "8\/1\/2024 12:31:07",
     "nameOfSchoolInstitution": "Main School",
     "Type of institution\/school": "Others (specify)",
     "Village name  if any": "Main School",
     "District": "North 24 Paragana",
     "State": "West Bengal",
     "fullAddressWithPinCode": "37c bediadanga, masjidbari bylane, kolkata 700040",
     "Name of the Principal and Management ": "Saratupa Majumder ",
     "Contact number of the Principal\/Management": 8420579906,
     "Name of the teacher\/coordinator for training and managing the library": "Manosij Bandhopadhay",
     "Contact details of the coordinator\/teacher": 8116424917,
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "No",
     "Number of Students - Balwadi - class 1": 222,
     "Number of Students - class 2 - class 4": 109,
     "Number of Students - class 5 and above": 47,
     "Referred by": "Bhumi",
     "Board affiliated to and Medium  of instruction(1)": "-",
     "Completed": true
    },
    {
     "Village name  if any": "guni",
     "District": "North 24 Paragana",
     "State": "West bengal",
     "fullAddressWithPinCode": "37c bediadanga, masjidbari bylane, kolkata 700039",
     "Name of the Principal and Management ": "Saratupa Majumder ",
     "Contact number of the Principal\/Management": 8420579906,
     "Name of the teacher\/coordinator for training and managing the library": "Manosij Bandhopadhay",
     "Contact details of the coordinator\/teacher": 8116424917,
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "No",
     "Number of Students - Balwadi - class 1": 68,
     "Number of Students - class 2 - class 4": 14,
     "Number of Students - class 5 and above": 0,
     "Referred by": "Bhumi",
     "Total No of Toys": 82,
     "Date of despatch ": "21\/06\/25",
     "Mode of despatch": "Courier circlepro",
     "Date of delivery": "26\/06\/25",
     "Completed": true
    },
    {
     "Village name  if any": "choto sahebkali",
     "District": "North 24 Paragana",
     "State": "West bengal",
     "fullAddressWithPinCode": "37c bediadanga, masjidbari bylane, kolkata 700040",
     "Name of the Principal and Management ": "Saratupa Majumder ",
     "Contact number of the Principal\/Management": 8420579906,
     "Name of the teacher\/coordinator for training and managing the library": "Manosij Bandhopadhay",
     "Contact details of the coordinator\/teacher": 8116424917,
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "No",
     "Number of Students - Balwadi - class 1": 75,
     "Number of Students - class 2 - class 4": 5,
     "Number of Students - class 5 and above": 0,
     "Referred by": "Bhumi",
     "Total No of Toys": 80,
     "Completed": true
    },
    {
     "Village name  if any": "main school",
     "District": "North 24 Paragana",
     "State": "West bengal",
     "Name of the Principal and Management ": "Saratupa Majumder ",
     "Contact number of the Principal\/Management": 8420579906,
     "Name of the teacher\/coordinator for training and managing the library": "Manosij Bandhopadhay",
     "Contact details of the coordinator\/teacher": 8116424917,
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "No",
     "Number of Students - Balwadi - class 1": 222,
     "Number of Students - class 2 - class 4": 109,
     "Number of Students - class 5 and above": 47,
     "Referred by": "Bhumi",
     "Total No of Toys": 378,
     "Completed": true
    },
    {
     "code": 45,
     "Timestamp": "8\/1\/2024 12:31:07",
     "nameOfSchoolInstitution": "Ganesh Mondal45",
     "Board affiliated to and Medium  of instruction": "Tamil Nadu State board and English",
     "Village name  if any": "ganesh mondol",
     "District": "North 24 Paragana",
     "State": "West bengal",
     "Name of the Principal and Management ": "Saratupa Majumder ",
     "Contact number of the Principal\/Management": 8420579906,
     "Name of the teacher\/coordinator for training and managing the library": "Manosij Bandhopadhay",
     "Contact details of the coordinator\/teacher": 8116424917,
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "No",
     "Number of Students - Balwadi - class 1": 129,
     "Number of Students - class 2 - class 4": 27,
     "Number of Students - class 5 and above": 0,
     "Referred by": "Bhumi",
     "Total No of Toys": 156,
     "Completed": true
    },
    {
     "Timestamp": "8\/1\/2024 11:32:00",
     "Type of institution\/school": "Others (specify)",
     "Village name  if any": "Junnar",
     "District": "Sawantwadi",
     "State": "maharashta",
     "fullAddressWithPinCode": "A-3\/Wanawadi, Pune 411040",
     "Name of the Principal and Management ": "Sanjiv Kadam",
     "Contact number of the Principal\/Management": 8805373500,
     "Name of the teacher\/coordinator for training and managing the library": "Sanjay Kadam",
     "Contact details of the coordinator\/teacher": 8805373500,
     "Is there a cupboard\/place for safekeeping of the toys": "yes",
     "Is there a room \/place to set up the library": "Yes",
     "Number of Students - Balwadi - class 1": 16,
     "Number of Students - class 2 - class 4": 0,
     "Number of Students - class 5 and above": 0,
     "Referred by": "sanjay\/venkat",
     "Total No of Toys": 16,
     "Date of despatch ": "10\/7\/24",
     "Mode of despatch": "Courier circlepro",
     "Date of delivery": "18\/7\/2024",
     "Completed": true
    }
   ]

